create table persons(
    id int primary key generated by default as identity,
    firstname varchar(100) not null,
    lastname varchar(100) not null,
    midlename varchar(100) not null,
    age int
)
